# Generated by Django 4.2.3 on 2024-10-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0002_alter_user_managers_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Designates whether this user must change their password at the next login.'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], default='normal', help_text='Designates the role of the user. The default is normal. ', max_length=10),
        ),
    ]
